on:
  push:
    branches:
      - main
  pull_request: {}

name: Test

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          # toolchain: nightly
          components: clippy

      - uses: calcit-lang/setup-cr@0.0.3
        with:
          version: "0.8.56"

      - run: cargo build --release

      - run: mkdir -p dylibs/ && ls target/release/ && cp -v target/release/libcalcit_dbt.* dylibs/

      - run: cr -1
